name: Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install Dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet build .\LegacyInstaller.sln --configuration Debug
    - name: Resolve Short Commit Hash
      if: startsWith(github.ref, 'refs/tags/') == false
      id: get_hash
      shell: bash
      run: echo ::set-output name=hash::`git rev-parse --short HEAD`
    - name: Upload LegacyInstaller Build
      if: startsWith(github.ref, 'refs/tags/') == false
      uses: actions/upload-artifact@v4
      with:
        name: LegacyInstaller-${{ steps.get_hash.outputs.hash }}
        path: ./LegacyInstaller/bin/x86/Debug/net6.0-windows
