name: ReleaseCancel changes

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup dotnet
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '6.0.x'
    - name: Install Dependencies
      run: dotnet restore
    - name: Build Project
      run: dotnet publish -p:PublishSingleFile=true -p:PublishReadyToRun=true -r win-x86 -c Release --self-contained true
    - name: Resolve Short Commit Hash
      if: startsWith(github.ref, 'refs/tags/')
      id: get_hash
      shell: bash
      run: echo ::set-output name=hash::`git rev-parse --short HEAD`
    - name: Archive Release
      uses: thedoctor0/zip-release@master
      with:
        type: 'zip'
        filename: LegacyInstaller-${{ steps.get_hash.outputs.hash }}.zip
        path: ./LegacyInstaller/bin/x86/Release/net6.0-windows/win-x86/publish/
    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        prerelease: false
        files: LegacyInstaller-${{ steps.get_hash.outputs.hash }}.zip
        repo_token: "${{ secrets.RELEASE_TOKEN }}"
